# Generated by Django 5.2.7 on 2026-01-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=False, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
