# Generated by Django 5.2.7 on 2026-03-07 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendor_logos/')),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('agency_name', models.CharField(blank=True, default='', max_length=255)),
                ('fringes_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('handling_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('markup_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('production_insurance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('production_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('post_markup_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('post_insurance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('post_tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_settings', to='users.vendor')),
            ],
            options={
                'db_table': 'vendor_settings',
            },
        ),
    ]
