# Generated by Django 5.2.7 on 2026-04-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_vendorsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_brief_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_brief_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
