# Generated by Django 5.2.7 on 2026-06-13 09:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_add_pending_brief_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorsettings",
            name="lead_notification_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="vendorsettings",
            name="slug",
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
