# Generated by Django 5.2.7 on 2026-06-13 09:29

import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models

import aivus_backend.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_vendorsettings_lead_notification_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorWebhookKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        default=aivus_backend.users.models.generate_webhook_key,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_key",
                        to="users.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_webhook_key",
            },
        ),
    ]
