# Generated by Django 5.2.7 on 2026-06-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_email_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsettings',
            name='custom_ai_instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
