# Generated by Django 5.2.7 on 2026-05-04 21:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreVendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pre_vendor_logos/')),
                ('portfolio_url', models.URLField(blank=True, default='')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], db_index=True, max_length=5)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('rank_label', models.CharField(blank=True, default='', max_length=64)),
                ('category_label', models.CharField(blank=True, default='', max_length=128)),
                ('sort_order', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Pre-Vendor',
                'verbose_name_plural': 'Pre-Vendors',
                'db_table': 'pre_vendor',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['language', 'sort_order'], name='pre_vendor_languag_98758a_idx')],
            },
        ),
    ]
