# Generated by Django 5.2.7 on 2025-10-26 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0002_team_alter_user_options_user_auth_type_user_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Initial status'), ('RFP', 'Request for Proposal'), ('REVIEWING', 'Under review'), ('ONGOING', 'In progress')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefs', to='users.client')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='briefs', to='users.team')),
            ],
            options={
                'db_table': 'brief',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Initial status'), ('RFP', 'Request for Proposal'), ('REVIEWING', 'Under review'), ('ONGOING', 'In progress')], max_length=20)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('profit', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('deadline', models.DateTimeField()),
                ('source', models.CharField(choices=[('PLATFORM', 'Default source'), ('UPLOAD', 'Uploaded')], max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('brief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='projects.brief')),
                ('parent_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_offers', to='projects.offer')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='users.vendor')),
            ],
            options={
                'db_table': 'offer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('options', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='catalog.entry')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='users.vendor')),
            ],
            options={
                'db_table': 'rate_card',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('XLS', 'Excel'), ('PDF', 'PDF')], max_length=10)),
                ('link', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('DELETED', 'Deleted')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='projects.offer')),
            ],
            options={
                'db_table': 'share',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_entries', to='catalog.entry')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_entries', to='projects.offer')),
            ],
            options={
                'db_table': 'offer_entry',
                'ordering': ['-created_at'],
                'unique_together': {('offer', 'entry')},
            },
        ),
        migrations.CreateModel(
            name='OfferRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('options', models.JSONField(default=list)),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_rates', to='projects.offer')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_rates', to='projects.rate')),
            ],
            options={
                'db_table': 'offer_rate',
                'ordering': ['-created_at'],
                'unique_together': {('offer', 'rate')},
            },
        ),
        migrations.CreateModel(
            name='SimpleRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_rates', to='catalog.entry')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_rates', to='users.vendor')),
            ],
            options={
                'db_table': 'rate',
                'ordering': ['-created_at'],
                'unique_together': {('vendor', 'entry')},
            },
        ),
    ]
