# Generated by Django 5.2.7 on 2025-11-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerrate',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rate',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
