# Generated by Django 5.2.7 on 2025-11-14 23:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_offerrate_description_alter_rate_description'),
        ('users', '0004_alter_user_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brief',
            name='team',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='vendor',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Initial status'), ('RFP', 'Request for Proposal'), ('REVIEWING', 'Under review'), ('ONGOING', 'In progress')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('brief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.brief')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='users.team')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='users.vendor')),
            ],
            options={
                'db_table': 'project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='projects.project'),
        ),
    ]
