# Generated by Django 5.2.7 on 2025-11-14 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_brief_team_remove_offer_brief_and_more'),
        ('users', '0004_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='users.team'),
        ),
    ]
