# Generated by Django 5.2.7 on 2026-02-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_add_project_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="client_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
