# Generated by Django 5.2.7 on 2026-02-12 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_unit_is_default'),
        ('projects', '0006_add_client_name_to_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerentry',
            options={'ordering': ['sort_order', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='offerentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='offer',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='offerentry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_entries', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='offerentry',
            name='client_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='offerentry',
            name='client_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='offerentry',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='offerentry',
            name='frontend_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='offerentry',
            name='is_linked_surcharge',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offerentry',
            name='item_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='offerentry',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='offerentry',
            name='market_range',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='offerentry',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='offerentry',
            name='show_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offerentry',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offerentry',
            name='surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='offerentry',
            name='tax_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='offerentry',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='offerentry',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_entries', to='catalog.entry'),
        ),
        migrations.RemoveField(
            model_name='offerentry',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='offerentry',
            name='details',
        ),
        migrations.RemoveField(
            model_name='offerentry',
            name='total_price',
        ),
    ]
