# Generated by Django 5.2.7 on 2026-02-12 21:25

import django.db.models.deletion
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_offerentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='share',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='share',
            name='token',
            field=models.CharField(db_index=True, default=secrets.token_urlsafe, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='share',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='share',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('DELETED', 'Deleted')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='share',
            name='type',
            field=models.CharField(blank=True, choices=[('XLS', 'Excel'), ('PDF', 'PDF')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='BriefOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brief_offers', to='projects.brief')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_brief_offers', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brief_offers', to='projects.offer')),
            ],
            options={
                'db_table': 'brief_offer',
                'ordering': ['-created_at'],
                'unique_together': {('brief', 'offer')},
            },
        ),
    ]
