# Generated by Django 5.2.7 on 2026-02-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_add_chat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
