# Generated by Django 5.2.7 on 2026-02-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_alter_offer_cost_alter_offer_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brief",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("REVIEWING", "Reviewing"),
                    ("COMPLETED", "Completed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="simplerate",
            name="value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
