# Generated by Django 5.2.7 on 2026-03-01 10:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_brief_status_alter_simplerate_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='bid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='cover_page_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='offer',
            name='media_placements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='offer',
            name='revision',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='term',
            field=models.CharField(blank=True, default='6 months', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='territory',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='brief',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWING', 'Reviewing'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Initial status'), ('RFP', 'Request for Proposal'), ('REVIEWING', 'Under review'), ('ONGOING', 'In progress')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='OfferDeliverable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('duration', models.CharField(blank=True, default='', max_length=20)),
                ('duration_unit', models.CharField(blank=True, default='Sec', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='projects.offer')),
            ],
            options={
                'db_table': 'offer_deliverable',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferScheduleEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase_type', models.CharField(default='Prep', max_length=100)),
                ('days', models.PositiveIntegerField(default=1)),
                ('hours_per_day', models.PositiveIntegerField(default=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='projects.offer')),
            ],
            options={
                'db_table': 'offer_schedule_entry',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
