# Generated by Django 5.2.7 on 2026-03-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_offer_bid_date_offer_cover_page_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='assumptions_exclusions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='offer',
            name='fringes_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='offer',
            name='handling_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='offer',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='offer',
            name='post_insurance_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='offer',
            name='post_markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='offer',
            name='post_tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='offer',
            name='production_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='offer',
            name='production_insurance_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='project',
            name='agency_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectcollaborator',
            name='role',
            field=models.CharField(choices=[('internal_user', 'Internal User'), ('external_user', 'External User'), ('producer', 'Producer'), ('agency_producer', 'Agency Producer')], default='internal_user', max_length=20),
        ),
    ]
