# Generated by Django 5.2.7 on 2026-03-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_offer_assumptions_exclusions_offer_fringes_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerentry',
            name='overtime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
