# Generated by Django 5.2.7 on 2026-04-04 17:45

import aivus_backend.projects.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_recalculate_offer_totals_with_fees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefMethodology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archetype_code', models.IntegerField(blank=True, db_index=True, null=True)),
                ('section_key', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'brief_methodology',
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='brief',
            name='anonymous_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='brief',
            name='archetypes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='brief',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brief',
            name='conversation_phase',
            field=models.CharField(choices=[('initial', 'Initial'), ('questioning', 'Questioning'), ('refining', 'Refining'), ('complete', 'Complete')], default='initial', max_length=20),
        ),
        migrations.AddField(
            model_name='brief',
            name='document_sections',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='brief',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brief',
            name='sections_status',
            field=models.JSONField(blank=True, default=aivus_backend.projects.models._default_sections_status),
        ),
        migrations.AddField(
            model_name='brief',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='brief',
            name='total_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='brief',
            name='total_input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brief',
            name='total_output_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brief',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='anonymous_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='model_used',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sections_changed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BriefFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_key', models.CharField(blank=True, default='', max_length=50)),
                ('rating', models.CharField(choices=[('up', 'Thumbs Up'), ('down', 'Thumbs Down')], max_length=10)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='projects.brief')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='projects.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brief_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brief_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
