# Generated by Django 5.2.7 on 2026-04-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_briefshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefshare',
            name='snapshot_document_sections',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='briefshare',
            name='snapshot_sections_status',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='briefshare',
            name='snapshot_structured_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='briefshare',
            name='snapshot_version',
            field=models.IntegerField(default=0),
        ),
    ]
