# Generated by Django 5.2.7 on 2026-04-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_briefshare_snapshot_document_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefshare',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='briefshare',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
