# Generated by Django 5.2.7 on 2026-04-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_briefshare_last_viewed_at_briefshare_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='questions_asked',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
