# Generated by Django 5.2.7 on 2026-04-11 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_populate_brief_methodology'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCallTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(blank=True, default='', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('request_messages', models.JSONField(blank=True, default=list)),
                ('request_params', models.JSONField(blank=True, default=dict)),
                ('response_raw', models.TextField(blank=True, default='')),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latency_ms', models.IntegerField(default=0)),
                ('sequence', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_traces', to='projects.chatmessage')),
            ],
            options={
                'db_table': 'llm_call_trace',
                'ordering': ['message_id', 'sequence', 'created_at'],
            },
        ),
    ]
