# Generated by Django 5.2.7 on 2026-04-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_prompt_finalization_two_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='kind',
            field=models.CharField(choices=[('chat', 'Chat'), ('feedback_request', 'Feedback Request'), ('feedback_reply_ack', 'Feedback Reply Ack')], db_index=True, default='chat', max_length=32),
        ),
    ]
