"""Seed BriefPrompt entry that holds STT phrase hints for the creative industry."""

from django.db import migrations

SLUG = "stt_industry_terms"
TITLE = "STT industry terms"

EN_TERMS = [
    "RFP",
    "brief",
    "treatment",
    "deck",
    "pitch",
    "moodboard",
    "storyboard",
    "shot list",
    "callsheet",
    "scout",
    "location scouting",
    "casting",
    "table read",
    "rehearsal",
    "principal photography",
    "shoot day",
    "talent",
    "SAG-AFTRA",
    "Union",
    "non-union",
    "buyout",
    "in perpetuity",
    "OOH",
    "paid social",
    "broadcast",
    "linear TV",
    "CTV",
    "deliverables",
    "hero film",
    "cutdowns",
    "stings",
    "bumpers",
    "key art",
    "key visual",
    "behind the scenes",
    "BTS",
    "DP",
    "director of photography",
    "gaffer",
    "key grip",
    "best boy",
    "1st AD",
    "2nd AD",
    "production designer",
    "art director",
    "wardrobe stylist",
    "MUA",
    "HMU",
    "VFX",
    "CGI",
    "compositing",
    "rotoscoping",
    "color grading",
    "color correction",
    "DI",
    "HDR",
    "Dolby Vision",
    "ProRes",
    "DNxHR",
    "anamorphic",
    "spherical",
    "ARRI Alexa",
    "RED Komodo",
    "Sony Venice",
    "b-roll",
    "rough cut",
    "fine cut",
    "picture lock",
    "online",
    "offline edit",
    "sound design",
    "foley",
    "ADR",
    "voiceover",
    "VO",
    "stems",
    "stock music",
    "needle drop",
    "AICP",
    "cost report",
    "kill fee",
    "treatment fee",
    "Aivus",
]

RU_TERMS = [
    "бриф",
    "тритмент",
    "тендер",
    "продакшн",
    "препродакшн",
    "постпродакшн",
    "съёмочный день",
    "съёмочная смена",
    "локация",
    "локейшн",
    "скаутинг",
    "кастинг",
    "режиссёр",
    "оператор",
    "продюсер",
    "сценарист",
    "гэффер",
    "грипп",
    "фокус-пуллер",
    "дольщик",
    "художник-постановщик",
    "костюмер",
    "стилист",
    "визажист",
    "монтаж",
    "монтажёр",
    "цветокоррекция",
    "цвет",
    "колор",
    "графика",
    "анимация",
    "VFX",
    "CGI",
    "звукорежиссёр",
    "звуковой дизайн",
    "озвучка",
    "закадровый текст",
    "сведение",
    "мастеринг",
    "сток",
    "стоковая музыка",
    "ролик",
    "ТВ-ролик",
    "тизер",
    "трейлер",
    "промо",
    "вертикалка",
    "горизонталка",
    "шот",
    "шот-лист",
    "раскадровка",
    "мудборд",
    "ключевой кадр",
    "хронометраж",
    "юзаж",
    "права",
    "лицензия",
    "Aivus",
]


def seed(apps, schema_editor):
    BriefPrompt = apps.get_model("projects", "BriefPrompt")
    BriefPrompt.objects.update_or_create(
        slug=SLUG,
        is_active=True,
        defaults={
            "title": TITLE,
            "body": " ",
            "version": 1,
            "metadata": {"en": EN_TERMS, "ru": RU_TERMS},
            "model_name": "",
        },
    )


def unseed(apps, schema_editor):
    BriefPrompt = apps.get_model("projects", "BriefPrompt")
    BriefPrompt.objects.filter(slug=SLUG).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0031_chat_message_kind"),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
