# Generated by Django 5.2.7 on 2026-05-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_alter_briefprompt_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='contact_email',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='brief',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
