# Generated by Django 5.2.7 on 2026-06-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_brief_contact_email_brief_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='pending_task_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
