# Generated by Django 5.2.7 on 2026-06-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_brief_pending_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefattachment',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
