# Generated by Django 5.2.7 on 2026-06-13 09:04

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0036_briefattachment_extracted_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="brief",
            name="source",
            field=models.CharField(
                choices=[
                    ("direct", "Direct"),
                    ("personal_link", "Personal vendor link"),
                    ("webhook", "Vendor webhook"),
                    ("wix", "Wix landing form"),
                ],
                db_index=True,
                default="direct",
                max_length=20,
            ),
        ),
    ]
