# Generated by Django 5.2.7 on 2026-06-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_brief_source'),
        ('users', '0012_vendorwebhookkey'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('brief__isnull', False), ('deleted_at__isnull', True)), fields=('vendor', 'brief'), name='uniq_active_project_per_vendor_brief'),
        ),
    ]
