# Generated by Django 5.2.7 on 2026-06-13 12:37

from django.db import migrations, models
from django.utils import timezone


def dedup_active_projects(apps, schema_editor):
    """Soft-delete duplicate active projects before the unique constraint lands.

    AddConstraint would fail on a prod database that already has more than one
    active (deleted_at IS NULL) project for the same (vendor, brief). For each such
    pair we keep the most recent project (by created_at) and soft-delete the rest,
    so the constraint can be added without a hard failure.
    """
    Project = apps.get_model('projects', 'Project')
    duplicate_groups = (
        Project.objects.filter(brief__isnull=False, deleted_at__isnull=True)
        .values('vendor_id', 'brief_id')
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
    )
    now = timezone.now()
    for group in duplicate_groups:
        active = list(
            Project.objects.filter(
                vendor_id=group['vendor_id'],
                brief_id=group['brief_id'],
                deleted_at__isnull=True,
            ).order_by('-created_at', '-id')
        )
        for stale in active[1:]:
            stale.deleted_at = now
            stale.save(update_fields=['deleted_at'])


def reverse_noop(apps, schema_editor):
    """Irreversible data fix: soft-deleting duplicates cannot be safely undone."""


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_brief_source'),
        ('users', '0012_vendorwebhookkey'),
    ]

    operations = [
        migrations.RunPython(dedup_active_projects, reverse_noop),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('brief__isnull', False), ('deleted_at__isnull', True)), fields=('vendor', 'brief'), name='uniq_active_project_per_vendor_brief'),
        ),
    ]
