# Generated by Django 5.2.7 on 2026-06-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_project_uniq_active_project_per_vendor_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='pending_task_error',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
