# Generated by Django 5.2.7 on 2026-06-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_brief_pending_task_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='emails_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
