# Generated by Django 5.2.7 on 2026-06-14 14:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0040_project_emails_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="brief",
            name="finalize_failed",
            field=models.BooleanField(default=False),
        ),
    ]
