# Generated by Django 5.2.7 on 2026-06-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_brief_finalize_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vendor_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
