# Generated by Django 5.2.7 on 2026-06-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_project_vendor_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='pending_task_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
