# Generated by Django 5.2.7 on 2026-07-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_seed_personal_link_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='source',
            field=models.CharField(choices=[('direct', 'Direct'), ('personal_link', 'Personal vendor link'), ('webhook', 'Vendor webhook'), ('wix', 'Wix landing form'), ('email', 'Inbound email')], db_index=True, default='direct', max_length=20),
        ),
        migrations.AlterField(
            model_name='briefprompt',
            name='slug',
            field=models.CharField(choices=[('main_system_prompt', 'Main system prompt'), ('finalization_prompt', 'Finalization prompt'), ('master_brief_template', 'Master brief template'), ('archetypes_reference', 'Archetypes reference'), ('stt_industry_terms', 'STT industry terms'), ('email_classification', 'Email classification'), ('email_reply', 'Email reply'), ('email_followup', 'Email follow-up'), ('agent_onboarding', 'Agent onboarding')], db_index=True, max_length=64),
        ),
    ]
