# Generated by Django 5.2.7 on 2026-07-10 14:37

import aivus_backend.email_agent.crypto
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0046_seed_email_agent_prompts'),
        ('users', '0014_vendorsettings_custom_ai_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail')], default='gmail', max_length=16)),
                ('role', models.CharField(choices=[('monitor', 'Monitoring inbox (read-only)'), ('agent', 'Agent mailbox (sends)')], max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('credential', aivus_backend.email_agent.crypto.EncryptedTextField(blank=True, default='')),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('uid_validity', models.CharField(blank=True, default='', max_length=64)),
                ('last_seen_uid', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('expired', 'Token expired'), ('revoked', 'Access revoked'), ('disconnected', 'Disconnected')], default='connected', max_length=16)),
                ('next_poll_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to='users.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_thread_id', models.CharField(db_index=True, max_length=128)),
                ('client_email', models.EmailField(blank=True, default='', max_length=254)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('canonical_subject', models.CharField(blank=True, default='', max_length=512)),
                ('state', models.CharField(choices=[('monitoring', 'Monitoring'), ('engaged', 'Engaged'), ('paused', 'Paused'), ('human_takeover', 'Human takeover')], default='monitoring', max_length=16)),
                ('paused_until', models.DateTimeField(blank=True, null=True)),
                ('participants', models.JSONField(blank=True, default=list)),
                ('last_history_id', models.CharField(blank=True, default='', max_length=64)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_threads', to='projects.project')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_threads', to='users.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_message_id', models.CharField(max_length=128)),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=8)),
                ('from_email', models.CharField(blank=True, default='', max_length=320)),
                ('to_emails', models.JSONField(blank=True, default=list)),
                ('cc_emails', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, default='', max_length=512)),
                ('body_clean', models.TextField(blank=True, default='')),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('intent', models.CharField(blank=True, choices=[('order', 'New order / lead'), ('question', 'Question on current project'), ('follow_up', 'Follow-up'), ('edits', 'Edits / changes'), ('junk', 'Junk / spam'), ('auto_reply', 'Auto-reply / OOO')], default='', max_length=16)),
                ('is_auto_reply', models.BooleanField(default=False)),
                ('message_id_header', models.CharField(blank=True, default='', max_length=512)),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=512)),
                ('references', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='email_agent.emailaccount')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='email_agent.emailthread')),
            ],
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_agent_logs', to='projects.project')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='email_agent.emailthread')),
            ],
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignee', models.CharField(choices=[('client', 'Client'), ('producer', 'Producer'), ('agent', 'Agent')], max_length=16)),
                ('text', models.TextField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('overdue', 'Overdue')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_action_items', to='projects.project')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='email_agent.emailmessage')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='email_agent.emailthread')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('discord', 'Discord')], default='email', max_length=16)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='users.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('delivered', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='email_agent.notificationchannel')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='users.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='OutboundDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('first_reply', 'First reply'), ('follow_up', 'Follow-up'), ('other', 'Other')], default='other', max_length=16)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('sent', 'Sent'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('provider_draft_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('in_reply_to_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='email_agent.emailmessage')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='email_agent.emailthread')),
            ],
        ),
        migrations.CreateModel(
            name='VendorAgentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('business_context', models.TextField(blank=True, default='')),
                ('tone', models.TextField(blank=True, default='')),
                ('notification_rules', models.JSONField(blank=True, default=dict)),
                ('special_rules', models.JSONField(blank=True, default=list)),
                ('autonomy_mode', models.CharField(choices=[('draft', 'Draft plus approval'), ('auto_safe', 'Auto-send safe replies')], default='draft', max_length=16)),
                ('producer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('working_hours', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to='users.vendor')),
            ],
        ),
        migrations.AddIndex(
            model_name='emailaccount',
            index=models.Index(fields=['status', 'next_poll_at'], name='email_agent_status_7e53bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('vendor', 'role'), name='uniq_active_account_per_vendor_role'),
        ),
        migrations.AddConstraint(
            model_name='emailthread',
            constraint=models.UniqueConstraint(fields=('vendor', 'provider_thread_id'), name='uniq_thread_per_vendor'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['message_id_header'], name='email_agent_message_18b572_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailmessage',
            constraint=models.UniqueConstraint(fields=('account', 'provider_message_id'), name='uniq_message_per_account'),
        ),
        migrations.AddIndex(
            model_name='agentlog',
            index=models.Index(fields=['thread', 'created_at'], name='email_agent_thread__3261ee_idx'),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['status', 'due_at'], name='email_agent_status_9df332_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['vendor', 'event', 'created_at'], name='email_agent_vendor__2e8d51_idx'),
        ),
        migrations.AddIndex(
            model_name='outbounddraft',
            index=models.Index(fields=['status', 'expires_at'], name='email_agent_status_b7feaf_idx'),
        ),
    ]
