# Generated by Django 5.2.7 on 2026-07-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_agent', '0001_initial'),
        ('users', '0014_vendorsettings_custom_ai_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='dedup_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='send_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outbounddraft',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['delivered', 'send_after'], name='email_agent_deliver_ac068d_idx'),
        ),
        migrations.AddConstraint(
            model_name='outbounddraft',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('in_reply_to_message',), name='uniq_pending_draft_per_inbound'),
        ),
    ]
