# Generated by Django 5.2.7 on 2026-07-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_agent', '0002_notifications_and_draft_guard'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailthread',
            name='memory',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
