# Generated by Django 5.2.7 on 2026-07-15 09:08

import aivus_backend.email_agent.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_agent', '0004_followup_tracking'),
        ('projects', '0050_email_classification_prompt_v3'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=aivus_backend.email_agent.models._email_attachment_upload_to)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_attachments', to='projects.brief')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email_agent.emailmessage')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email_agent.emailthread')),
            ],
            options={
                'indexes': [models.Index(fields=['thread', 'created_at'], name='email_agent_thread__a138a0_idx')],
            },
        ),
    ]
