# Generated by Django 5.2.7 on 2026-07-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_agent', '0005_emailattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='provider_message_id',
            field=models.CharField(max_length=998),
        ),
        migrations.AlterField(
            model_name='emailthread',
            name='provider_thread_id',
            field=models.CharField(db_index=True, max_length=998),
        ),
        migrations.AlterField(
            model_name='outbounddraft',
            name='provider_draft_id',
            field=models.CharField(blank=True, default='', max_length=998),
        ),
    ]
