# Generated by Django 5.2.7 on 2026-07-19 13:48

import aivus_backend.email_agent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_agent', '0006_alter_emailmessage_provider_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachment',
            name='file',
            field=models.FileField(max_length=500, upload_to=aivus_backend.email_agent.models._email_attachment_upload_to),
        ),
    ]
