# Generated by Django 5.2.7 on 2026-07-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_agent', '0007_alter_emailattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='in_reply_to',
            field=models.CharField(blank=True, default='', max_length=998),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='message_id_header',
            field=models.CharField(blank=True, default='', max_length=998),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=998),
        ),
        migrations.AlterField(
            model_name='emailthread',
            name='canonical_subject',
            field=models.CharField(blank=True, default='', max_length=998),
        ),
    ]
