#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


exec gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app \
  --config /app/config/gunicorn_conf.py \
  --workers 4 \
  --preload \
  --timeout 180 \
  --graceful-timeout 30 \
  --access-logfile - \
  --error-logfile - \
  --log-level info
