#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py migrate --noinput
python /app/manage.py collectstatic --noinput

exec gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app \
  --workers 4 \
  --timeout 180 \
  --graceful-timeout 30 \
  --access-logfile - \
  --error-logfile - \
  --log-level info
