# Generated by Django 5.2.7 on 2026-01-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_seed_initial_catalog_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
