# Generated by Django 5.2.7 on 2026-02-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_entry_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='is_default',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
