# Generated by Django 5.2.7 on 2026-03-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_fix_day_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='entry',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
