# Generated by Django 5.2.7 on 2026-03-13 17:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_category_code_entry_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('production', 'Production'), ('post_production', 'Post-Production'), ('pre_production', 'Pre-Production')], max_length=20), blank=True, default=list, size=None),
        ),
    ]
